### ISSUE TITLE
💥milsymbol 1.0.0💥

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#61]
~~Sometime after #6 is implemented,~~ I will try to start working on milsymbol 1.0.

This will involve but not be limited to:

- [x]  Major refactoring of the code and cleaning.
- [x]  API changes to a bunch of the helper functions, this is part of cleaning the code and getting better code structure.
- [x]  #9 Splitting milsymbol in multiple modules.
- [x]  Build mechanism to build milsymbol with only the needed modules.
- [x] #34 Writing new markdown based documentation ~~(Might be that I migrate to JSDoc during the code refactoring.)~~
- [x] #63 Update Feint/Dummy indicator 
- [x] #64 Display upside down '?' for invalid icons 
- [X] #80 Renaming namespace from MS to ms
- [X] #82 Adding tactical points to main milsymbol 
- [X] #83 Adding support for tactical points in APP6-B

Add any missing features you want here.

**Comment by spatialillusions** [comment]
Added 
 #82 Adding tactical points to main milsymbol
 #83 Adding support for tactical points in APP6-B
 #64 Display upside down '?' for invalid icons
 #63 Update Feint/Dummy indicator
But next version of milsymbol will likely be 1.0.0

**Comment by spatialillusions** [comment]
Removed
"(I can't promise tactical graphics, but I'm not saying that its not going to happen.)"
Not in 1.0.0

**Comment by spatialillusions** [comment]
- [X] #82 Adding tactical points to main milsymbol

**Comment by spatialillusions** [comment]
- [X ] #63 Update Feint/Dummy indicator

**Comment by spatialillusions** [comment]
Adding 
- [ ] #80 Renaming namespace from MS to ms

**Comment by spatialillusions** [comment]
With the current tasks in mind, the plan is to release milsymbol 1.0.0 before end of Mars 2017.

**Comment by spatialillusions** [comment]
Won't migrate to JSDoc now.

**Comment by spatialillusions** [comment]
- [X] #80 Renaming namespace from MS to ms

**Comment by spatialillusions** [comment]
#83 Adding support for tactical points in APP6-B

**Comment by spatialillusions** [comment]
- [x] #64 Display upside down '?' for invalid icons 

Milsymbol 1.0.0 is now feature complete.

Release will be done when documentation and homepage is updated.

**Comment by spatialillusions** [comment]
Will release new version during the weekend.
